name: Memory Profile Comparison

on: pull_request

jobs:
  compare-memory-profiles:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Generate memory profiles
      run: |
        git checkout ${{ github.head_ref }}
        make profile-memory OUTFILE_SUFFIX=.feat || { echo "Failed to generate feature profile"; ls -l; cat Makefile; exit 1; }
        git checkout main
        make profile-memory OUTFILE_SUFFIX=.main || { echo "Failed to generate main profile"; ls -l; cat Makefile; exit 1; }

    - name: Compare memory profiles
      run: |
        ls -l
        if [ ! -f memprofile.main.out ] || [ ! -f memprofile.feat.out ]; then
          echo "Error: One or both memory profile files are missing."
          exit 1
        fi
        make profile-memory-compare BASE_FILE=memprofile.main.out FEAT_FILE=memprofile.feat.out > memory-profile-comparison.text || { echo "Failed to compare profiles"; cat Makefile; exit 1; }
        echo "Memory Profile Comparison:"
        cat memory-profile-comparison.text

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: memory-profiles
        path: |
          memprofile.main.out
          memprofile.main.text
          memprofile.feat.out
          memprofile.feat.text
          memory-profile-comparison.text
