name: Test SDK
on:
  pull_request:
    path: '**/*'

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: 'Set up GCP SDK for downloading test data'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Test
        run: go test -v ./...
