name: Test SDK
on:
  pull_request:
    path: '**/*'

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: Run unit tests
        run: make test
